### ISSUE TITLE
NuGet installation fails using .NET framework 4.6.2

### ISSUE THREAD

**Issue by JamesJansenVanRensburg** [Yubico/Yubico.NET.SDK#11]
Hi, 

I am new to the SDK and tried installing it using NuGet. This however fails with the following error:

_Could not install package 'Yubico.NativeShims 1.3.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author._				

Any advice or help would be appreciated.

**Comment by jzylkin** [comment]
I am having a very similar issue, and I see it on .NET Framework 4.7.2 and 4.6.1 (these are the only ones I have tried.)

**Comment by JamesJansenVanRensburg** [comment]
The 1.1.0 version seems to work on .NET 4.6.2 so I think it might work for others as well.

**Comment by GregDomzalski** [comment]
Thank you for the reports. Yes, we've been getting other reports about this as well. It appears that for whatever reason, NuGet has no problem resolving this package for .NET Core / .NET 5+ based projects, but cannot resolve it for .NET Framework.

We will try and get a fix out sometime this week.

Using any version of the SDK prior to 1.3.0 should avoid this issue, as would targeting .NET 6 (or other "core" based version of .NET).

I'll post back on this thread once the updated NativeShims package has been released.

**Comment by GregDomzalski** [comment]
Hi folks,

I wanted to give an update to this investigation. Unfortunately it seems like it's a compounding set of issues:

1. The way `packages.config` and `PackageReferences` resolves NuGet packages seems to be different. `packages.config` will refuse to resolve the NativeShims package, however `PackageReferences` has no problem. We _can_ make `packages.config` work if we lie and say that the NativeShims package "depends" on .NETStandard2.0. I'd rather not, but we can if it comes down to it.
2. Assuming we do the above workaround, `packages.config` also doesn't seem smart enough to resolve the correct native DLL to copy it into the bin folder of the project build output. I currently have no idea how to work around this from the SDK angle - the only fix that I see is a change to the csproj file of the consuming project... `PackageReferences` has no problem and does the right thing.
3. .NET Framework, despite implementing the .NET Standard 2.0 spec, behaves differently than cross-platform .NET when it comes to DLLImport name resolution. In cross-platform .NET, it is common (even encouraged) to leave the extension off of the library. This is because shared libraries have different extensions on other platforms (`dylib` on mac, `so` on linux). .NET Framework, on the other hand, seems to require the file extension. It will not try to resolve the name by appending `dll` on it automatically.

So - I think I may have a path forward here, at least for the PackageReferences case. But, I'd love some feedback from you all:

Are you still using packages.config?  If so, would you be able to move to PackageReferences?

(And a bonus, half-serious question: Have you tried using .NET 6? 😄 )

There seem to be far, far fewer issues when using PackageReferences.

**Comment by JamesJansenVanRensburg** [comment]
Hi Greg, 

For my own usecase, I am working on a very old legacy code base which uses packages.config and I wish we could upgrade! That would solve so many problems. I think at least from my side we will reevaluate if its worth it implementing webauthn in our applications since the solution to multiple other packages seem to be upgrading the versions. Thanks so much for the time and investigation!

**Comment by herrjemand** [comment]
Same issue on our side

**Comment by GregDomzalski** [comment]
At this time, there's unfortunately not a lot that we can do.

The current suggestion from the team is to create your own MSBuild Target that can pull this binary in from the expanded NuGet package. The implementation of which is left to the reader.

I know this isn't a great answer for those of you stuck on packages.config. But at this current time, it's hard to justify prioritizing fixing what seems like a bug (on .NET's side) for a technology that's been abandoned by .NET.

If anyone has had luck with this issue or any similar issue like this in the past, I would love to hear from you. We're not opposed to taking a fix.

In the meantime, I'll leave this issue open so that others can upvote or add more information that may help bump the priority. If your team has an existing relationship with our SE, Product, or Developer Program team, please work with them so that we may better understand the impact to your product.

**Comment by GregDomzalski** [comment]
Alright - an update for this issue!

I hope if .NET Framework 4.x users try SDK 1.6.1 they will find this issue resolved!!

After more research, I finally found another project having a similar problem. They fixed this by introducing an MSBuild targets file into the NuGet package that will copy the native binary over to the build output directory. I used that as an example and expanded it to handle all of the various build architectures the SDK supports.

Then, it looks like NuGet has added support for a "buildTransitive" asset that will flow the targets file up through the dependency change (NativeShims -> Core -> YubiKey -> _YourCode_).

I've tested this against a .NET Framework 4.8 based project and it seems to work. No more missing DLL error since the build is now locating the correct binaries.

.NET Core/5+ users should not be affected, since this was already working for them.

I'm afraid Packages.Config is still not supported (untested). It may work, it may not. It may work if you directly consume the Yubico.NativeShims package, it may not. Since Microsoft has abandoned this in favor of PackageReferences, I simply don't have any documentation from them to know what I can expect in terms of supporting these advanced features. Apologies to those stuck on Packages.config. Upgrade if you can - but I understand if you can't. Unfortunately our small team needs to draw the line somewhere and focus on the long-term supported technologies. If someone has a solution that would work for packages.config and it's a reasonably-sized fix, I would be happy to take it as a community contribution to the project.

I'll leave this issue open for a few days in case anyone has feedback/comments/suggestions or are still running into problems with this.

Thank you all for being so patient. This ended up being a "straight-forward" fix. Arriving at what exactly this fix was was the challenge 😄
