### ISSUE TITLE
[Question]: How to invalidate MiniDriver cache?

### ISSUE THREAD

**Issue by bplatypus** [Yubico/Yubico.NET.SDK#161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is your question?

How can I make sure that I get the new certificate from a Yubikey **via MiniDriver** when I call ImportCertificate?

How can we invalidate the MiniDriver cache?

We're doing something like this to read the certificate:
`var privateKey = IntPtr.Zero;
CryptAcquireContext(ref smartCardContext, containerName, providerName, PInvoke.PROV_RSA_FULL, PInvoke.CRYPT_VERIFYCONTEXT)
CryptGetUserKey(smartCardContext, PInvoke.AT_KEYEXCHANGE, ref privateKey);
CryptGetKeyParam(privateKey, PInvoke.KP_CERTIFICATE, null, ref certificateBufferSize, 0)
CryptReleaseContext(smartCardContext, 0)`

We receive the 'old' certificate not the new imported one.

We also have this kind of issue when we switch between multiple Yubikeys.

**Comment by DennisDyallo** [comment]
Hi @bplatypus ! The YubiKey SmartCard Minidriver is a separate YubiKey product. 

Here are the docs for the minidriver. 
https://docs.yubico.com/software/yubikey/tools/minidriver/index.html

If you can't find your solution there then I suggest you start a ticket [here](https://support.yubico.com/hc/en-us/requests/new) and pick the best option, I will get routed to the support channel.

**Comment by romerod** [comment]
Just for anyone else stumbling over this problem:

Make sure to change the card holder unique id, after updating the certificate:

var chuid = new CardholderUniqueId();
chuid.SetRandomGuid();
pivSession.WriteObject(chuid);

And use CNG (ncrypt.h) instead of wincrypt.h (deprecated) to read the certificates.

Side note: Using wincrypt.h with yubikey also doesn't detect switching between plugged yubikeys.
